### ISSUE TITLE
Ability to simplify datatype of a model's field

### ISSUE THREAD

**Issue by ecorkevin** [ngnjs/chassis-lib#16]
An idea for simpler models could be to define the data type by just using it as the key. For example,

```js
var cat = new Animal({
  name: String,
  age: Number
})
```

would be a bit cleaner than
```js
var cat = new Animal({
  name: {
    type: String
  },
  age: {
    type: Number
  }
})
```
if you don't need to define anything else

**Comment by coreybutler** [comment]
Version [1.0.97](https://github.com/ngnjs/chassis-lib/releases/tag/1.0.97) now supports this. Also, for reference, the proper syntax would be:

```js
let Animal = new NGN.DATA.Model({
  fields: {
    name: String,
    age: Number,
    type: String
  }
})

let MyPet = new Animal({
  name: 'Jake',
  age: 13,
  type: 'dog'
})
```

The original syntax still works as well, and setting a data type to `null` still defaults to a `String` (which is how it was previously).
