### ISSUE TITLE
NGN.ref.someNamedDomRef.value = Number fails

### ISSUE THREAD

**Issue by coreybutler** [ngnjs/chassis-lib#25]
When a reference to a form field exists, passing a numeric value fails.

@ecorkevin - The error was complaining about a `trim()` method. I didn't have a chance to die into this. If you can track down where the problem is and write a regression test, it would be really helpful.

**Comment by ecorkevin** [comment]
I am unable to replicate this with the following, and will need a bit more description:

```html
<form>
  First name:<br>
  <input type="text" name="firstname"><br>
  Last name:<br>
  <input type="text" name="lastname">
</form>
```
```js
NGN.ref.create('someRef', 'input[name="lastname"]')
NGN.ref.someRef.value = 100
```

**Comment by coreybutler** [comment]
Closing since this seems like an isolated case.
