### ISSUE TITLE
What is the license of library?

### ISSUE THREAD

**Issue by nolsherry** [ngnjs/chassis-lib#29]
Hello @coreybutler  ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs/) project.
We want to host this library.
There are some problems about the license of library which need to confirm with you. 
I downloaded the library from [npm](https://www.npmjs.com/package/ngn-chassis), and I found the `license` in `package.json` is `BSD3`, but I also found  the `license` in `bower.json` from [github](https://github.com/ngnjs/chassis-lib/blob/1.0.138/bower.json) website is `MIT`.
Which one is the correct license of the library?
thanks!

cdnjs/cdnjs#8287

**Comment by coreybutler** [comment]
I'm sorry for the confusion, I didn't realize this was the case. This is officially being released under the **BSD-3-Clause** license. I'm going to leave this open so I remember to update the bower file accordingly.

**Comment by nolsherry** [comment]
@coreybutler thanks for your response! 
By the way, I also found the `package.json` file from [github ](https://github.com/ngnjs/chassis-lib/blob/master/package.json) website is different from [npm](https://www.npmjs.com/package/ngn-chassis), and the `package.json` which downloaded from npm is lack of some field information, such as `keywords`, `description`. Which source is better?

**Comment by coreybutler** [comment]
@nolsherry The absolute best source is the [release page](https://github.com/ngnjs/chassis-lib/releases). It looks like our build process is skipping the LICENSE file, but I could update that.

Some clarification details:

Chassis/NGN is built from multiple repositories. This repo, chassis-lib (and it's opinionated extension library, chassis-libx) are the primary front end libraries. They share a common core code base with a Node library... things like the data models/stores/proxies/etc. We have a build process that runs for every release, producing developer/debug/production versions of this library & the others. This gets published as a github release, and this is also where bower is sourcing from. We even use this as the source for our own CDN (just an S3/Cloudflare setup).

The npm package is not truly designed for UI users. It is designed for node & pseudo-ui-environments... the primary use case being NW.js & Electron. Requiring chassis-lib in one of these environments automatically injects the code in the HTML page when necessary. It's just a wrapper.

The honest truth is you're a little ahead of the game, and chassis-lib is a small cog in a much bigger effort that we're still putting finishing touches on. We've just put chassis-lib through the "real world" test as the base of the upcoming [Fenix](http://github.com/coreybutler/fenix) 3.0.0 release, but we also built a new CSS layout system called Chassis-SASS, which implements [SymbioCSS](https://github.com/gbdrummer/symbiocss). There's also shared code across a really small web component library, a mixin library, devtools extensions, backend Node.js libraries, & a Docker-based microservice platform that glues it all together. As you've seen, we have some cleanup work to do. We're on top of it, but it's just two of us :)

**Comment by coreybutler** [comment]
The license file has been updated in bower (and everywhere else) for v1.1.1+
