### ISSUE TITLE
NGN.HTTP.importTo() style

### ISSUE THREAD

**Issue by coreybutler** [ngnjs/chassis-lib#4]
Importing remote HTML fragments into a a DOM element may create a flash of unstyled content, or worse, display content prematurely. 

@gbdrummer - Should we automatically add a "standard" CSS class to the parent element to represent state? For example:

**Beginning Document**

``` html
<div id="mydiv"></div>
```

**Execute the following JS code:**

``` js
NGN.HTTP.importTo('/path/to/template.html', document.getElementById('mydiv'))
```

When the JS is executed, it would first change the HTML to

``` html
<div id="mydiv" class="ngn-loading"></div>
```

Then the import function will retrieve the `/path/to/template.html` and insert it into the DOM, i.e.

``` html
<div id="mydiv" class="ngn-loading"><... some new code here .../></div>
```

When the DOM insertion is complete, the class would be removed, ultimately resulting in:

``` html
<div id="mydiv"><... some new code here.../></div>
```

**Bigger Question**

The big question is whether we want to assume any kind of state with the JS. The state is self-invoked by the Chassis `importTo` method, so it makes sense in this case. There are several other states that could be applied with other Chassis functions (NGN.DOM.ready, SVG updates, etc). We don't need the JS to provide any CSS at all, but we'd need to document the NGN classes (like `ngn-loading`).

If the library automatically adds some standard classes, users can define their own CSS for them. They could hide the element while it's loading, create a loadmask over it, or even listen for CSS events in modern browsers to do whatever they want (like forward to the NGN.BUS). This would also mean you could create basic themes around standard class names (without preventing users from overriding them if they so choose).

**Comment by gbdrummer** [comment]
This is definitely a problem that needs a solution, although this is essentially the AngularJS approach (They also have "ng-cloak" which will prevent the FOUC). I don't really have a better idea at the moment, but I do wonder if there is a way to accomplish this without manipulating the dom.

**Comment by coreybutler** [comment]
I suppose we could just fire events directly to the bus instead of automatically changing class names and responding to DOM changes. We could fire `import.prefetch`, `import.fetched`, and `import.rendered` to the NGN.BUS along with a reference to the new URL/FileContent/DOM element as an argument to the event handler.

I don't see a way of changing the visual state of a page without manipulating the DOM in some way... a classname would have to be specified. However; using the event approach gives users a choice to respond to these events or ignore them.


We could always create another NGNX extension to apply classes as a response to these events, like:

```js
NGN.BUS.pool('import.', {
  prefetch: function (url) {
    console.log('Fetching', url)
    document.getElementById('someId').classList.add('ngn-loading')
  },
  retrieved: function (filecontent) {
    console.log('Retrieved', filecontent)
  },
  rendered: function (newDomElement) {
    document.getElementById('someId').classList.remove('ngn-loading')
    console.log(newDomElement)
  }
})
```

**Comment by coreybutler** [comment]
After reflecting on this and creating several additional libraries, I think it would be best to ignore this feature. This should be a developer choice, not a forced opinion. The `NGNX.VIEW.Registry` concept of initialization can and should handle this.

@gbdrummer - thoughts? If you agree, I'm going to close this issue.
